apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "payload-signing-service"
  namespace: "helsemelding"
  labels:
    "team": "helsemelding"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingresses:
    - "https://helsemelding-payload-signing-service.intern.dev.nav.no"
  accessPolicy:
    outbound:
    inbound:
      rules:
        - application: state-service
          cluster: dev-gcp
  envFrom:
    - secret: helsemelding-keystore-pwd
  filesFrom:
    - secret: helsemelding-keystore
      mountPath: /var/run/secrets/helsemelding-keystore
  env:
    - name: KEYSTORE_FILE_SIGN
      value: /var/run/secrets/helsemelding-keystore/nav_signing_test.p12
    - name: NAV_CERTIFICATE_ALIAS
      value: nav_virksomhet
