apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "payload-processing-service"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingresses:
    - "https://payload-processing-service.intern.dev.nav.no"
  accessPolicy:
    outbound:
    inbound:
      rules:
        - application: state-service
          cluster: dev-gcp
  envFrom:
    - secret: ebms-keystore-pwd-2025
  filesFrom:
    - secret: ebms-keystore-2025
      mountPath: /var/run/secrets/ebms-keystore-2025
  env:
    - name: KEYSTORE_FILE_SIGN
      value: /var/run/secrets/ebms-keystore-2025/nav_signing_test.p12
